### ISSUE TITLE
Add tabs to new post form

### ISSUE THREAD

**Issue by destch** [danielchavez97/Forum#1]

**Comment by destch** [comment]
https://jsfiddle.net/cyberwombat/yAFLr/

**Comment by danielchavez97** [comment]
- [add text post wysiwyg editor]
- [make links embedable]
- [media upload posts]

**Comment by danielchavez97** [comment]
- [ ] fd

**Comment by destch** [comment]
- [x] text posts and wysiwyg editor
- [x] media uploads
- [ ] link posts, find a way to identfy iframe embeddable media
